# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A markov sampler using Rcpp
#' @description A random walk Metropolis sampler for generating the standard Laplace distribution
#' @param n Number of random numbers
#' @param a Number of random numbers
#' @param b Number of random numbers
#' @return Returns random sequence and rejection probability
#' @examples
#' \dontrun{
#' C_Gibbs <-(25,2,2)
#' }
#' @export
C_Gibbs <- function(n, a, b) {
    .Call(`_StatComp21030_C_Gibbs`, n, a, b)
}

rcpp_hello_world <- function() {
    .Call(`_StatComp21030_rcpp_hello_world`)
}

